#!/usr/bin/env node
// Bundles the browser-side Vue app (src/ui/client/main.ts) together
// with Vue 3 into a single IIFE, then writes it to
// src/ui/client-bundle.gen.ts as an exported string constant so the
// Worker can inline it inside a <script> tag in the /ui response.
//
// The generated file is checked in. Re-run this whenever Vue or the
// client source changes (`pnpm build:ui`).

import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import Vue from "unplugin-vue/esbuild";

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, "..");
const entry = path.join(repoRoot, "src/ui/client/main.ts");
const outFile = path.join(repoRoot, "src/ui/client-bundle.gen.ts");

const pkg = JSON.parse(
  await readFile(path.join(repoRoot, "package.json"), "utf8"),
);
const vueVersion = pkg.dependencies?.vue ?? "unknown";

const result = await build({
  entryPoints: [entry],
  bundle: true,
  minify: true,
  format: "iife",
  target: ["es2022"],
  platform: "browser",
  write: false,
  // Vue's ESM-bundler build expects these flags to be defined by the
  // downstream bundler. Drop the options API to shave a few KB.
  define: {
    __VUE_OPTIONS_API__: "false",
    __VUE_PROD_DEVTOOLS__: "false",
    __VUE_PROD_HYDRATION_MISMATCH_DETAILS__: "false",
    "process.env.NODE_ENV": '"production"',
  },
  legalComments: "none",
  treeShaking: true,
  // Force the runtime-only Vue build. With SFCs precompiled at build time,
  // the template compiler is never called; this alias makes that explicit
  // and keeps a future accidental `import { compile } from "vue"` from
  // re-introducing the compiler into the bundle (which would also fail
  // under the /ui CSP's `unsafe-eval` ban).
  alias: {
    vue: "vue/dist/vue.runtime.esm-bundler.js",
  },
  plugins: [Vue({ isProduction: true })],
});

const out = result.outputFiles?.[0];
if (!out) {
  throw new Error("esbuild produced no output");
}
const bundle = out.text;
const sizeKb = (bundle.length / 1024).toFixed(1);

// Store the bundle as a backtick-quoted template literal and escape the
// three characters that would terminate the literal prematurely.
const escaped = bundle
  .replace(/\\/g, "\\\\")
  .replace(/`/g, "\\`")
  .replace(/\$\{/g, "\\${");

const header = `// AUTO-GENERATED by scripts/build-ui.mjs. Do not edit by hand.
// Source: src/ui/client/main.ts (Vue ${vueVersion})
// Regenerate with: pnpm build:ui
`;

const contents = `${header}
export const clientBundle = \`${escaped}\`;
`;

await writeFile(outFile, contents, "utf8");
console.log(`build-ui: wrote ${path.relative(repoRoot, outFile)} (${sizeKb} KB minified)`);
