#!/usr/bin/env node
// Reads woff2 files from @fontsource/{inter,jetbrains-mono}, base64-encodes
// them, and emits src/ui/fonts.gen.ts exporting a CSS string of @font-face
// rules. The resulting CSS is inlined into the /ui page.ts <style> so the
// dashboard ships its fonts without any external network requests — the CSP
// stays locked to default-src 'none'.
//
// Re-run with `pnpm build:fonts` (also chained from `pnpm build:ui`).

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, "..");
const outFile = path.join(repoRoot, "src/ui/fonts.gen.ts");

// Only Latin subset; the dashboard UI copy is English. Saves ~80 KB over
// pulling every subset. Weights pinned to what the design actually uses.
const faces = [
  { family: "Inter", weight: 400, file: "inter/files/inter-latin-400-normal.woff2" },
  { family: "Inter", weight: 500, file: "inter/files/inter-latin-500-normal.woff2" },
  { family: "Inter", weight: 600, file: "inter/files/inter-latin-600-normal.woff2" },
  { family: "Inter", weight: 700, file: "inter/files/inter-latin-700-normal.woff2" },
  { family: "JetBrains Mono", weight: 400, file: "jetbrains-mono/files/jetbrains-mono-latin-400-normal.woff2" },
  { family: "JetBrains Mono", weight: 500, file: "jetbrains-mono/files/jetbrains-mono-latin-500-normal.woff2" },
];

const rules = [];
let totalBytes = 0;
for (const face of faces) {
  const abs = path.join(repoRoot, "node_modules/@fontsource", face.file);
  const buf = await readFile(abs);
  totalBytes += buf.byteLength;
  const b64 = buf.toString("base64");
  rules.push(
    `@font-face{font-family:'${face.family}';font-style:normal;font-weight:${face.weight};font-display:swap;src:url(data:font/woff2;base64,${b64}) format('woff2')}`,
  );
}
const css = rules.join("");

const header = `// AUTO-GENERATED by scripts/build-fonts.mjs. Do not edit by hand.
// Re-generate with: pnpm build:fonts
`;
const contents = `${header}
export const fontsCss = ${JSON.stringify(css)};
`;

await writeFile(outFile, contents, "utf8");
const kb = (totalBytes / 1024).toFixed(1);
const b64Kb = (css.length / 1024).toFixed(1);
console.log(
  `build-fonts: wrote ${path.relative(repoRoot, outFile)} (${faces.length} faces, ${kb} KB raw, ${b64Kb} KB base64)`,
);
